version: '3.8'

services:
  # --- BASE DE DATOS GEESPACIAL ---
  db:
    image: postgis/postgis:16-3.4
    container_name: spatia_postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spatia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- GESTOR DE BASE DE DATOS (GUI) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: spatia_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: jluna@spatiaconsulting.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db

  # --- MOTOR 1: COCHE (Puerto 5000) ---
  osrm-drive:
    image: osrm/osrm-backend:latest
    container_name: spatia_osrm_drive
    restart: unless-stopped
    volumes:
      # Montamos solo la carpeta de coche procesada
      - ./osrm_data/car:/data
    ports:
      - "5000:5000"
    # Arranca el servidor usando el archivo que generamos manualmente
    command: "osrm-routed --algorithm mld /data/input.osrm"

  # --- MOTOR 2: PIE (Puerto 5001) ---
  osrm-walk:
    image: osrm/osrm-backend:latest
    container_name: spatia_osrm_walk
    restart: unless-stopped
    volumes:
      # Montamos solo la carpeta de pie procesada
      - ./osrm_data/foot:/data
    ports:
      - "5001:5000" # Mapeamos puerto 5000 interno al 5001 de tu PC
    # Arranca el servidor usando el archivo que generamos manualmente
    command: "osrm-routed --algorithm mld /data/input.osrm"

volumes:
  pgdata:
    driver: local