services:
  db:
    image: postgis/postgis:16-3.4
    container_name: spatia_postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spatia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: spatia_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: jluna@spatiaconsulting.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db

  osrm:
    image: osrm/osrm-backend:latest
    container_name: spatia_osrm
    working_dir: /data
    volumes:
      - ./osrm_data:/data
    command: >
      bash -c "
      osrm-extract -p /opt/car.lua /data/madrid.osm.pbf &&
      osrm-partition /data/madrid.osrm &&
      osrm-customize /data/madrid.osrm &&
      osrm-routed --algorithm mld /data/madrid.osrm
      "
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - db

volumes:
  pgdata:
